version: '3'

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    networks:
      - postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/umbrella_app
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - postgres

volumes:
  postgres_data:

networks: 
  postgres:
    driver: bridge