# Generated by Django 2.2.6 on 2019-10-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191026_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='fecha_inicial',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='fecha_final',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='estatus',
            field=models.CharField(choices=[('I', 'Inicio'), ('T', 'Termino')], default='', max_length=1),
            preserve_default=False,
        ),
    ]
