# Generated by Django 2.2.6 on 2019-10-27 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191027_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='sobmrilla',
            new_name='sombrilla',
        ),
    ]
